In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\data sets\fraud_dataset_example.csv")

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.tree import DecisionTreeClassifier

In [4]:
data

step      type      amount     nameOrig  oldbalanceOrg  \
0          1   PAYMENT     9839.64  C1231006815      170136.00   
1          1   PAYMENT     1864.28  C1666544295       21249.00   
2          1  TRANSFER      181.00  C1305486145         181.00   
3          1  CASH_OUT      181.00   C840083671         181.00   
4          1   PAYMENT    11668.14  C2048537720       41554.00   
...      ...       ...         ...          ...            ...   
101608    10   PAYMENT     7477.02   C513257306         785.00   
101609    10  CASH_OUT   282252.35   C210473293      220339.29   
101610    10   PAYMENT    17289.01   C807582280           0.00   
101611    10  TRANSFER  1347146.45  C1315779140        1605.00   
101612    10  CASH_OUT   469539.21   C515691325       31133.00   

        newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
0            160296.36  M1979787155            0.00            0.00        0   
1             19384.72  M2044282225            0.00            0.00        0   
2                 0.00   C553264065            0.00            0.00        1   
3                 0.00    C38997010        21182.00            0.00        1   
4             29885.86  M1230701703            0.00            0.00        0   
...                ...          ...             ...             ...      ...   
101608            0.00   M524833426            0.00            0.00        0   
101609            0.00  C1172042998        95156.01        91286.97        0   
101610            0.00   M334249577            0.00            0.00        0   
101611            0.00  C1631408038       541639.43      2186953.43        0   
101612            0.00  C1383702768            0.00       469539.21        0   

        isFlaggedFraud  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  
...                ...  
101608               0  
101609               0  
101610               0  
101611               0  
101612               0  

[101613 rows x 11 columns]

In [5]:
data.isFraud.value_counts()

isFraud
0    101497
1       116
Name: count, dtype: int64

In [6]:
data.drop(columns = ['nameOrig','nameDest','isFlaggedFraud'], axis = 1 , inplace = True)

In [7]:
data

step      type      amount  oldbalanceOrg  newbalanceOrig  \
0          1   PAYMENT     9839.64      170136.00       160296.36   
1          1   PAYMENT     1864.28       21249.00        19384.72   
2          1  TRANSFER      181.00         181.00            0.00   
3          1  CASH_OUT      181.00         181.00            0.00   
4          1   PAYMENT    11668.14       41554.00        29885.86   
...      ...       ...         ...            ...             ...   
101608    10   PAYMENT     7477.02         785.00            0.00   
101609    10  CASH_OUT   282252.35      220339.29            0.00   
101610    10   PAYMENT    17289.01           0.00            0.00   
101611    10  TRANSFER  1347146.45        1605.00            0.00   
101612    10  CASH_OUT   469539.21       31133.00            0.00   

        oldbalanceDest  newbalanceDest  isFraud  
0                 0.00            0.00        0  
1                 0.00            0.00        0  
2                 0.00            0.00        1  
3             21182.00            0.00        1  
4                 0.00            0.00        0  
...                ...             ...      ...  
101608            0.00            0.00        0  
101609        95156.01        91286.97        0  
101610            0.00            0.00        0  
101611       541639.43      2186953.43        0  
101612            0.00       469539.21        0  

[101613 rows x 8 columns]

In [8]:
x = data.drop('isFraud', axis = 1)
y = data[['isFraud']] 

In [9]:
#splitting the data
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2)

In [10]:
xtest

step      type     amount  oldbalanceOrg  newbalanceOrig  \
5378      5   PAYMENT    9080.77       72543.00        63462.23   
74437    10   CASH_IN  125452.09       20688.00       146140.09   
5578      6   PAYMENT    4424.31      405068.00       400643.69   
93762    10   PAYMENT   16858.10        7659.32            0.00   
49692     9  CASH_OUT   41403.17           0.00            0.00   
...     ...       ...        ...            ...             ...   
21067     8   CASH_IN  349483.51     6220783.28      6570266.80   
62179     9  CASH_OUT  442500.97           0.00            0.00   
8853      7   PAYMENT    7426.25       20250.00        12823.75   
64488     9   CASH_IN    2575.08    26538894.62     26541469.70   
84081    10  CASH_OUT  152538.26        1169.00            0.00   

       oldbalanceDest  newbalanceDest  
5378             0.00            0.00  
74437       140602.75        15150.67  
5578             0.00            0.00  
93762            0.00            0.00  
49692        42432.59        16019.71  
...               ...             ...  
21067       447669.37       193704.45  
62179      9410550.44     10365457.67  
8853             0.00            0.00  
64488       730069.03      1434208.83  
84081        30556.74       183095.00  

[20323 rows x 7 columns]

In [11]:
#one_hot encoding
trf1 = ColumnTransformer([('ohe',OneHotEncoder(handle_unknown = 'ignore',sparse_output = False),[1])]
                        ,remainder = 'passthrough')

In [12]:
trf1

ColumnTransformer(remainder='passthrough',
                  transformers=[('ohe',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 [1])])

In [13]:
# Scaling
trf2 = ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,8))])

In [14]:
# train the model
trf3 = DecisionTreeClassifier()

In [15]:
pipe = make_pipeline(trf1,trf2,trf3)

In [16]:
pipe

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1])])),
                ('columntransformer-2',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 8, None))])),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [19]:
pipe.fit(xtrain,ytrain)

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1])])),
                ('columntransformer-2',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 8, None))])),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [21]:
# Predict
y_pred = pipe.predict(xtest)

In [22]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(ytest,y_pred)

0.9981794026472469

In [27]:
confusion_matrix(ytest,y_pred)

array([[20278,    19],
       [   18,     8]], dtype=int64)

In [28]:
print(classification_report(ytest,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     20297
           1       0.30      0.31      0.30        26

    accuracy                           1.00     20323
   macro avg       0.65      0.65      0.65     20323
weighted avg       1.00      1.00      1.00     20323



In [29]:
import pickle
#pickle.dump(pipe,open('fraud1.pkl','wb'))

In [31]:
f = open("fraud.pkl", 'rb')

In [32]:
f1 = pickle.load(f)

In [33]:
#only displaying the values in which isFraud=1
data[data['isFraud']==1]

step      type     amount  oldbalanceOrg  newbalanceOrig  \
2         1  TRANSFER     181.00         181.00             0.0   
3         1  CASH_OUT     181.00         181.00             0.0   
251       1  TRANSFER    2806.00        2806.00             0.0   
252       1  CASH_OUT    2806.00        2806.00             0.0   
680       1  TRANSFER   20128.00       20128.00             0.0   
...     ...       ...        ...            ...             ...   
77745    10  CASH_OUT  277970.88           0.00             0.0   
90070    10  TRANSFER   93810.76       93810.76             0.0   
90071    10  CASH_OUT   93810.76       93810.76             0.0   
99371    10  TRANSFER  503405.88      503405.88             0.0   
99372    10  CASH_OUT  503405.88      503405.88             0.0   

       oldbalanceDest  newbalanceDest  isFraud  
2                0.00            0.00        1  
3            21182.00            0.00        1  
251              0.00            0.00        1  
252          26202.00            0.00        1  
680              0.00            0.00        1  
...               ...             ...      ...  
77745            0.00       277970.88        1  
90070            0.00            0.00        1  
90071      4096048.05      4189858.81        1  
99371            0.00            0.00        1  
99372        29669.00       533074.88        1  

[116 rows x 8 columns]

In [34]:
f1.predict([[10,'TRANSFER',503405,	503405.00,	0,	0,	0]])

C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

### balancing data

In [39]:
from imblearn.over_sampling import RandomOverSampler

In [40]:
RandomOverSampler = RandomOverSampler(random_state = 42)

In [41]:
RandomOverSampler

RandomOverSampler(random_state=42)

In [43]:
x_resampled,y_resampled = RandomOverSampler.fit_resample(x,y)

In [44]:
x_resampled.shape,y_resampled.shape

((202994, 7), (202994, 1))

In [45]:
y_resampled[y_resampled==1].shape

(202994, 1)

In [46]:
y_resampled[y_resampled==0].shape

(202994, 1)

In [89]:
yresampled.isnull().sum()

isFraud    0
dtype: int64

In [48]:
# train the model again (after balancing)
dtc = DecisionTreeClassifier()

In [49]:
dtc

DecisionTreeClassifier()

In [50]:
from sklearn.linear_model import LogisticRegression

In [51]:
lr = LogisticRegression()

In [52]:
lr

LogisticRegression()

In [55]:
xtr,xte,ytr,yte = train_test_split(x_resampled,y_resampled,test_size = 0.33)

In [56]:
pipe.fit(xtr,ytr)

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1])])),
                ('columntransformer-2',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 8, None))])),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [57]:
# Predict
y_pred = pipe.predict(xte)

In [58]:
y_pred

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

In [59]:
#accuracy (after balancing the data)
accuracy_score(yte,y_pred)

0.9995670931048382

In [61]:
print(classification_report(yte,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     33411
           1       1.00      1.00      1.00     33578

    accuracy                           1.00     66989
   macro avg       1.00      1.00      1.00     66989
weighted avg       1.00      1.00      1.00     66989

